--- po/Makefile.orig	2009-01-20 18:03:29.000000000 +0800
+++ po/Makefile	2013-06-16 00:19:27.860330345 +0900
@@ -1,5 +1,4 @@
 PLUGIN = wavelet-sharpen
-LOCALEDIR = /usr/share/locale
 LANGUAGES = de ru it pl et
 
 # END CONFIG ##################################################################
@@ -24,7 +23,7 @@
 
 install: $(LANGUAGES)
 	for L in $(LANGUAGES); \
-	do install -v -m 0644 $$L.mo "$(LOCALEDIR)/$$L/LC_MESSAGES/gimp20-$(PLUGIN)-plug-in.mo"; \
+	do install -D -v -m 0644 $$L.mo "$(LOCALEDIR)/$$L/LC_MESSAGES/gimp20-$(PLUGIN)-plug-in.mo"; \
 done
 
 uninstall: $(LANGUAGES)
